# Generated by Django 3.2.8 on 2021-12-17 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='_rank',
        ),
        migrations.RemoveField(
            model_name='post',
            name='_rank',
        ),
        migrations.AddField(
            model_name='comment',
            name='rank',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='post',
            name='rank',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='author',
            name='rank',
            field=models.IntegerField(default=0),
        ),
    ]
