# Generated by Django 3.2.8 on 2021-12-27 21:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_alter_usercategory_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercategory',
            name='created_datetime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
